version: 2.1

orbs:
  php: circleci/php@1.1
  wp-svn: studiopress/wp-svn@0.2

jobs:
  lint:
    docker:
      - image: wordpress:php8.2-fpm-alpine
    steps:
      - checkout
      - run:
          name: Install Composer
          command: |
            mkdir -p ~/project/bin
            cd ~/project/bin
            echo 'export PATH=$HOME/project/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            EXPECTED_SIGNATURE=$(curl -s https://composer.github.io/installer.sig)
            ACTUAL_SIGNATURE=$(php -r "echo hash_file('sha384', 'composer-setup.php');")
            [[ "$EXPECTED_SIGNATURE" == "$ACTUAL_SIGNATURE" ]] && php composer-setup.php --install-dir=/root/project/bin --filename=composer || exit 1
            rm composer-setup.php
            composer config -g github-protocols https && composer config -g repo.packagist composer https://packagist.org
      - php/install-packages
      - run: composer phpcs

workflows:
  test-deploy:
    jobs:
      - lint
      - wp-svn/deploy:
          context: genesis-svn
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
          requires:
            - lint
          dry-run: true
      - approval-for-deploy-tested-up-to-bump:
          requires:
            - lint
          type: approval
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^bump-tested-up-to.*/
      - wp-svn/deploy-tested-up-to-bump:
          context: genesis-svn
          requires:
            - approval-for-deploy-tested-up-to-bump
